name: ocr

on:
  pull_request:
    branches: [ "main" ]
  push:
  workflow_dispatch:

jobs:
  pytesseract:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies - Tesseract 4.1.1 and Python packages
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr
          python -m pip install --upgrade pip
          python -m pip install -r ./ocr/requirements.txt
      - name: Code checking
        run: pre-commit run --all-files
      - name: Run unittests
        run: |
          cd ocr
          python -m pytest ./test

  tesseract:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo name
        run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:ocr"
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}_ocr:latest
