name: ocr

on:
  pull_request:
    branches: [ "main" ]
  push:
  workflow_dispatch:

jobs:
  ci-ocr:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo name
        run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:ocr"
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}_ocr:latest
