name: python

on:
  pull_request:
    branches: [ "main" ]
  push:
  workflow_dispatch:

jobs:
  check-python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "pypy3.10"]
    name: Python ${{ matrix.python-version }}
    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r ./python/requirements.txt
      - name: Run pre-commit
        run: pre-commit run --all-files

  ci-python:
    runs-on: ubuntu-latest
    steps:
      - name: Get repo name
        run: echo "REPO_NAME=$(basename ${{ github.repository }})" >> $GITHUB_ENV
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:python"
          push: true
          file: Dockerfile
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.REPO_NAME }}:latest
